targets:
  $default:
    builders:
      generators|annotations:
        enabled: true

builders:
  generators:
    target: ":copy_annotation_gen"
    import: "package:copy_annotation_gen/copy_annotation_gen.dart"
    builder_factories: ["generateCopyExtension"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
