name: copy_annotation
description: Annotation for generating extension on object copy with code generation
version: 0.0.1
homepage: https://github.com/soethan98/copy_ext_generator

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
